package poc1.model.vo;

import poc1.model.extensions.MyViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 08 15:24:37 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends MyViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }
}

