package poc1.model.am;

import poc1.model.extensions.MyApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 08 10:39:39 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyAppModuleDefImpl extends MyApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MyAppModuleDefImpl() {
    }
}

