package poc1.model.am;

import poc1.model.extensions.MyApplicationModuleImpl;
import poc1.model.extensions.MyViewObjectImpl;
import poc1.model.vo.EmployeesVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 08 10:39:39 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyAppModuleImpl extends MyApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MyAppModuleImpl() {
    }

    /**
     * Container's getter for CountriesVO1.
     * @return CountriesVO1
     */
    public MyViewObjectImpl getCountriesVO1() {
        return (MyViewObjectImpl) findViewObject("CountriesVO1");
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public EmployeesVOImpl getEmployeesVO1() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for CountriesVOViewUsage.
     * @return CountriesVOViewUsage
     */
    public MyViewObjectImpl getCountriesVOViewUsage() {
        return (MyViewObjectImpl) findViewObject("CountriesVOViewUsage");
    }

    /**
     * Container's getter for EmployeesVOViewUsage.
     * @return EmployeesVOViewUsage
     */
    public EmployeesVOImpl getEmployeesVOViewUsage() {
        return (EmployeesVOImpl) findViewObject("EmployeesVOViewUsage");
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public MyViewObjectImpl getDepartmentsVOViewUsage() {
        return (MyViewObjectImpl) findViewObject("DepartmentsVOViewUsage");
    }
}

